function [fitresult, gof] = createFit(x, z)
%CREATEFIT(X,Z)
%  Create a fit.
%
%  Data for  fit:
%see excel file for details
%      X Input(log10[Na+]): x
%      Y Output (ratiometric data): z
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also SFIT.

%  Auto-generated by MATLAB on 18-Feb-2023 17:28:07


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, z );

% Set up fittype and options.
ft = fittype( 'U + (L-U)/(1 + exp(-4*log(3)*(x-xmid)/xscale80))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Robust = 'LAR';
opts.StartPoint = [3.643 10.2332 0.485375648722841 0.8002804688888];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'z vs. x', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'z', 'Interpreter', 'none' );
grid on


