function [fitresult, gof] = createFit1(x, mc)
%CREATEFIT1(X,MC)
%  Create a fit.
%
%  Data for 'Increase green absorption' fit:
%      X Input : x
%      Y Output: mc
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Apr-2023 19:54:50


%% Fit: 'Increase green absorption'.
[xData, yData] = prepareCurveData( x, mc );

% Set up fittype and options.
ft = fittype( 'U + (L-U)/(1 + exp(-4*log(3)*(x-xmid)/xscale80))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Robust = 'LAR';
opts.StartPoint = [4.48 13.39 0.54972360829114 0.91719366382981];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Increase green absorption' );
h = plot( fitresult, xData, yData );
legend( h, 'mc vs. x', 'Increase green absorption', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'mc', 'Interpreter', 'none' );
grid on


