function [fitresult, gof] = createFit1(x, z)
%CREATEFIT1(X,Z)
%  Create a fit.
%
%  Data for 'R-DiFC' fit:
%      X  : sodium concentration in log units
%      Z  : Ratiometric signal 
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Apr-2023 19:47:07


%% Fit: 'R-DiFC'.
[xData, yData] = prepareCurveData( x, z );

% Set up fittype and options.
ft = fittype( 'U + (L-U)/(1 + exp(-4*log(3)*(x-xmid)/xscale80))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Robust = 'LAR';
opts.StartPoint = [3.694 10.19387 0.959291425205444 0.547215529963803];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'R-DiFC' );
h = plot( fitresult, xData, yData );
legend( h, 'z vs. x', 'R-DiFC', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'z', 'Interpreter', 'none' );
grid on


